### ISSUE TITLE
FixUnlimitedPotionsBug Tweak causes Cast Spell - Activate Item [Single Use] to fail as GetItemActivated() returns OBJECT_INVALID

### ISSUE THREAD

**Issue by plenarius** [nwnxee/unified#1029]
Steps to recreate:
Create a module, give it an `OnActivateItem` script
Set the script to 
```c
void main()
{
    object oItem = GetItemActivated();
    if (!GetIsObjectValid(oItem))
    {
        SendMessageToPC(GetFirstPC(),"WOT?");
        return;
    }
}
```
Create an item that is Cast Spell : Activate Item [Touch] [Single Use]
`export NWNX_TWEAKS_FIX_UNLIMITED_POTIONS_BUG=y`
Use the item in game and it fails to find the oItem.

**Comment by GoLoT** [comment]
I was too hopeful when I thought that the item wasn't needed in any scripts. I only checked spell scripts.

I left a note in #966 with a possible workaround, moving the item instead of removing it instantly so the OID is still valid but the player isn't able to move/stack the item before it's deleted.

If anyone wants to take a stab at it, changing the exclusive hook to a shared hook and moving the item somewhere (can items be sent to the limbo?) instead of changing the `nTimeFromNow` should fix the issue. The original Destroy event should take care of removing the item after that.

I have very limited time atm so I don't know when I will be able to fix it.
