### ISSUE TITLE
Latest download link not working anymore correctly with 'latest'

### ISSUE THREAD

**Issue by ich777** [nwnxee/unified#1124]
Hello,

got a quick qustion why is the version number for the latest version 'latest'?
That breaks my Docker container for Unraid since it tries to download this:

`https://github.com/nwnxee/unified/releases/download/build${NWNEE_V}/NWNX-EE.zip`

If the latest release is named latest it tries at:
`https://github.com/nwnxee/unified/releases/download/buildlatest/NWNX-EE.zip`

But it should be something like:
`https://github.com/nwnxee/unified/releases/download/build8193.16/NWNX-EE.zip`

Is this now the default way the development builds are released?

**Comment by plenarius** [comment]
Hello, we've changed our build system so the latest is always the developmental release and not the tagged release with a version. We felt like tagged versions don't really mean a ton since bug fixes can come immediately after tagged releases and a more accurate state of nwnx per nwn version is now tagged as latest.

Perhaps you may have given us thought to how we should tag this latest release with latest8193.16 instead of just latest so we always have the last build for the specific nwn version accurate. I'll follow up after some discussion.

**Comment by plenarius** [comment]
I should add, how does your docker image derive `${NWNEE_V}` any way?

**Comment by plenarius** [comment]
Hello, I found your script and I suggest you parse out the latest version that NWNX:EE currently supports of NWN:EE to do this:

Instead of:
```sh
LAT_V="$(curl -s https://api.github.com/repos/nwnxee/unified/releases/latest | grep tag_name | cut -d '"' -f4 | cut -d 'd' -f2)"
```

do:

```sh
LAT_V="$(curl -s https://api.github.com/repos/nwnxee/unified/contents/NWNXLib/Platform/ASLR.cpp | jq -r .content | base64 -d | grep NWNX_EXPECT_VERSION | cut -d"(" -f2 | cut -d")" -f1 | sed 's/, /./)"
```

**Comment by ich777** [comment]
@plenarius Thank you for the quick answer, working as charm right now, container already updated. ;)

Changed the command a little bit since there was a missing ' to:

`LAT_V="$(curl -s https://api.github.com/repos/nwnxee/unified/contents/NWNXLib/Platform/ASLR.cpp | jq -r .content | base64 -d | grep NWNX_EXPECT_VERSION | cut -d '(' -f2 | cut -d ')' -f1 | sed 's/, /./')"`
