### ISSUE TITLE
Missing 'names' plugin in official builds

### ISSUE THREAD

**Issue by weavejester** [nwnxee/unified#154]
I notice that there's no `NWNX_Names.so` plugin in the official builds. Is that because this plugin isn't ready and shouldn't be used? Or is it omitted for another reason?

**Comment by mtijanic** [comment]
The names plugin is by far the most complicated, and would require manual maintenance every time the base game is updated. So, for now it is disabled. Either we'll enable it with 1.75, since the NWN stable releases are now rare enough, or it will be implemented directly in the base game.

Either way, for now it is not usable.

**Comment by weavejester** [comment]
Thanks for the quick explanation!
