### ISSUE TITLE
NWNXHaks - Allow to Log into server without haks/custom TLK

### ISSUE THREAD

**Issue by torradmin** [nwnxee/unified#36]
int SetHakHidden(string sHak, int nLevel = 1);
void SetPlayerEnhanced(object oPC, int nEnhanced);
int SetFallBackTLK(string sTLK);

from: https://github.com/jd28/nwnx-haks

Basically, allow players to log into servers with haks without having any haks or custom TLK installed or having to download any such. This would make it MUCH easier for players to get into the server's lobby room to read up on the server rules etc before actually starting playing.

**Comment by Christian-Vassallo** [comment]
It's not totally true.

It allows the player to login without asking for a specific hak/tlk.

However, if the player does not use this hak/tlk, the functionalities are not working.
Example: if you don't use the TLK, you cannot see the custom description.

Another important thing: if you don't load the HAK correctly, especially for toolsets, your client is going to crash.

I guess that the purpouse of NWN_Hak has been missunderstood.
The NWNX_Haks allows to manage which hak should be read instead of another.
Example: in HAK0 you have cls_feat/skills for Paladin. Then, in HAK1 you have again cls_feat/skills for Anti-Paladin that is paladin-based class.
When the player login, you can understand if it is paladin or antipaladin (i.e. by deity description) and then decide to mask or now hak 0.

That's how this plugin work. It is not possible to have custom content only server side (excepted for 2da that are used only by the system)

**Comment by mtijanic** [comment]
Is this still desirable with nwsync available?

**Comment by torradmin** [comment]
Hard to say, probably less so. The idea was that you could know if players had downloaded the haks or not, and if not, you could just allow them to visit the "rules areas" to get to know the server before downloading all the haks and creating your actual character.

In a way, it would be best with another feature where you could automatically create a pre-generated character for a player just for getting on to the server before creating your own.

NWSync at its current state is still quite slow for downloading giant haks and players do have to have that disk space available before knowing whether they agree with the server's rules and setting.

**Comment by mtijanic** [comment]
The thing is that this might not be possible with nwsync (without nwncx). So you might be left with a choice between nwsync and nwnx_haks, in which case I don't see anyone picking the latter.

As for the other request, that's something to look into - I wanted that for another module anyway, where you can't make characters but just pick an existing one.

**Comment by jd28** [comment]
As the person who wrote the original, I don't see it having much value in a world with NWSync, but I've never used that.  The original impetus was:

- A very low friction initial login.  E,g. rules areas, links to resources/content, etc.
- The ability to make a tiered download system.  I.e. Tier 1: Top hak, Custom TLK (very small download).  Tier 2: Custom content, models, tilesets, etc (very large download).  Keep in mind that this was more valuable for PWs that already had significant worlds built with common content, but were wanting to add more custom content with as little friction as possible. 
- The ability to hide haks that were strictly server side resources.

Of the three I'd only see the first still being relevant.  And I think the best solution to that in the long run would be replacing the campaign/module/PW lobby with an external program that used nwmain as a dumb loader.  Kind of like [neverrun](https://neverwintervault.org/project/nwn1/other/tool/neverrun) was where the interface allowed for server information to be communicated in a much friendlier/broader way.  But that would be up to Beamdog, they might already have that in their long-term plans.

**Comment by mtijanic** [comment]
> A very low friction initial login. E,g. rules areas, links to resources/content, etc.

Assuming most servers move to nwsync (only a couple of high profile ones haven't yet), the way it works is you get a significant download when you just install the game and pick the first server. E.g. if the server uses CEP2, it'll take maybe 10 minutes to download and join it (but you don't have to hunt the haks externally). Then, if that's not the server for you, you try the next one... this one uses 50% of the content from CEP, and 50% from others... now you wait 5 minutes to download. Since the amount of CC available is very limited (note we're talking about file contents, not renamed copies), after 3-4 servers you could very quickly jump into any others because you already have most of the content downloaded.

With download speeds being an order of magnitude faster than in 1.69 days I can't imagine anyone actually using this, especially if it means you can't use nwsync at all. Basically you'd be forcing the player to find your website out of game and download and install crap manually (which they probably already have from other servers) for the benefit of being able to read the rules IG. Might as well read them on the website.

**Comment by jd28** [comment]
I was merely giving the history behind the original plugin, I pretty clearly said I didn't think it was of much value today.  NWSync and this old plugin are/were about the same thing: making NWN and PW creators hard work more accessible.

**Comment by mtijanic** [comment]
Sorry, didn't want to come across as confrontational, the historical context is much appreciated. I don't want to close any feature request as WNF if anyone still wants it; but at the same time, I don't want to have it open and have someone potentially spend a lot of effort implementing something that has no real use anymore. So, @torradmin and @zunath , do you guys still want this feature?

**Comment by zunath** [comment]
Nah. Nwsync makes this a non-issue for me. I'm fine with closing it out

**Comment by jd28** [comment]
I'd say close it, if someone wanted to contribute it... then fine, I think it'd be orthogonal to NWSync as servers using that don't do the hak broadcast at all and not cause any issues, but I don't think it's worth anyone's time.

**Comment by torradmin** [comment]
I never was thinking anyone had to do it. Maybe if it was of interest to them and they found the time. But yeah as nwsync gets to a more useable state this isn't really that important. Nwsync really needs an option to be able to read the player's hak/tlk folders for existing data before doing the long initial download from the manifest for e.g the CEP.
