### ISSUE TITLE
[feature_request] Direct way to catch and hook Epic dodge event

### ISSUE THREAD

**Issue by silent-rock** [nwnxee/unified#456]
Would it be possible to add to `nwnx_events` plugin the direct way to catch and hook the successful Epic dodge event?

Example usage:
* skipping the event
* creating additional conditional statements before the event
* creating additional effect after the event

**Comment by plenarius** [comment]
The only way this can work is hooking `HasFeat` which is used many times a tick. @mtijanic mentioned in Discord a while back that maybe the function can be hooked per specific need (i.e. just catch the Epic Dodge check and send the event, otherwise pass through). Combined with the new [DispatchListMode](https://github.com/nwnxee/unified/pull/564) it may ease things a touch. Just putting down some thoughts in case someone else looks at this.
