### ISSUE TITLE
[possible bug] Utils::AsNWSArea & Utils::AsNWSItem

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#584]
I feel, in my heart, just looking at these that they are wrong.  I have no proof tho, still setting up Ghidra.  Both of these classes inherit other classes before CGameObject.  Logically I don't see how a pointer to CNWSArea could be equal to, or static_cast from, a pointer to CNWSArea::CGameObject.  Same with CNWSItem.

https://github.com/nwnxee/unified/blob/28e307b0a031fa9295e99e7c0ae9574e6fb9d8ad/NWNXLib/Utils.cpp#L63-L68

https://github.com/nwnxee/unified/blob/28e307b0a031fa9295e99e7c0ae9574e6fb9d8ad/NWNXLib/Utils.cpp#L93-L98

**Comment by GoLoT** [comment]
Do you mean a `static_cast` wouldn't work for multiple inheritance and `dynamic_cast` should be used instead? I might be wrong but I think it does when upcasting as long as the derived class actually inherits the base class.

In this case the object type is checked to make sure the derived class is of a compatible type (i.e. inherits the base class) so I don't see why it wouldn't work.

**Comment by mtijanic** [comment]
> I feel, in my heart, just looking at these that they are wrong

I know exactly what you're thinking, and I've had bugs due to this before until I worked it out. Really wish someone would have told me beforehand. I'll spell it out here in detail for posterity too.

### Somewhat short version:
#### Single inheritance chain
If you have a single inheritance chain, like A->B->C, and you're certain that the object is actually of type C (via `m_nObjectType` or something), all your casts, both upcast and downcast, static, C-style, etc, are effectively `reinterpret_cast`. Meaning, the pointer value remains the same, just the type of the variable changes.
This isn't the case for CNWSItem and CNWSArea, but just adding for completeness and intro

#### Multiple inheritance
Like the case of CNWSItem, you can have class hierarchy like:
```
 E->D
     \
A->B->C
```
And you have an object of type C, the casts behave differently:
* `static_cast` requires full definition of all types (A,B,C,D,E) to be included, and will then do the correct thing and move the pointer to the right place. You're still good to cast to any of the types.
* `reinterpret_cast` only works properly for the first chain. So you could `reinterpret_cast` a `CNWSArea*` to a `CNWArea*`, but not to `CGameObject*`. Generally, it should be entirely avoided in these cases.
* C-style cast (`(C*)pObj`), and this is a real WTF, behaves differently based on what is included. It will look for the definitions of all types (A,B,C,D,E). If all of them are found, it behaves like static cast. If any of them are missing, it will silently switch over to reinterpret_cast without any warning whatsoever. So removing an include could break your code while still passing a compile.

Since then, we do not use C-style casts anywhere, precisely because casting CNWSArea silently broke.


(as a general rule, I never close issues filed by others, so please close unless you feel something is still missing)

**Comment by mtijanic** [comment]
Oh, side note on
>  still setting up Ghidra.

There's nothing to see in Ghidra here, these are entirely nixie utility functions with the source. You might see functions with the same name in Ghidra, but they function differently. They're basically poor man's RTTI implemented in NWN, something like this:

```C
struct CGameObject
{
    virtual CNWSObject* AsNWSObject() { return nullptr; }
    virtual CNWSCreature* AsNWSCreature() { return nullptr; }
    virtual CNWSItem* AsNWSItem() { return nullptr; }
    virtual CNWSArea* AsNWSArea() { return nullptr; }
    ...
};
struct CNWSObject : CGameObject
{
    virtual CNWSObject* AsNWSObject() { return this; }
};
struct CNWSCreature: CNWSObject 
{
    virtual CNWSCreature* AsNWSCreature() { return this; }
};
//etc
```
These share names and purpose with the NWNX:EE util functions, but they are an entirely separate mechanism that we don't have access to from the current API. The nwnx64 _should_ allow us to use this, but I haven't tried yet.

**Comment by jd28** [comment]
Thank you so much for taking the time to write that up.  I never expected that `static_cast` would be able to do that!  Cheers!
