### ISSUE TITLE
Add support for 'exclusive' hook daisy chaining

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#627]
With the coming of nwnx:ee64 and hopefully dotnet core.  Users of nwnx:ee shouldn't have to choose between nwnx_profiler and a scripting engine or even between one scripting engine or another.  And most likely they'd want to be able to profile these things too.

Access to a core DelayCommand service could facilitate the creation of other non-scripting engine use cases too.  Like a simple NWNX_Callback plugin, e.g. call a script every N seconds, like a psuedo-heartbeat.

**Comment by jd28** [comment]
Sorry meant to link to a basic sketch of the idea: https://gist.github.com/jd28/a5df0f80b9b79d6f3b0f2b4c62fd8161

**Comment by mtijanic** [comment]
Would the ability to daisy-chain 'exclusive' hooks, and some way to specify where you want to hook (first, default, last) solve these needs? Profilers would hook first, and would always forward. Scripting engines would hook default, and forward the call if they can't service it. Something like instead of `m_hook->CallOriginal` you get `m_hook->CallNext`?

This seems like a lower level and more generic solution to me, though I'm not opposed to the scripting service option if it offers more features.

**Comment by jd28** [comment]
I rather like what you've suggested.  Maybe just move a bit of common code to utils and it seems like that would work very nicely.

That could also provide a possible mechanism for a Resman, each plugin that wanted to serve files could just hook the respective functions and chain the request.

**Comment by mtijanic** [comment]
Should also support shared hooks around exclusive hooks (if desired), to address issues like #397

**Comment by Daztek** [comment]
Would getting the return value of a shared hook in the `AFTER_ORIGINAL` calltype be something that could be done easily? See: #503

Another nice to have would be a `GetIsCalledBy()` function, if possible

**Comment by mtijanic** [comment]
Sure. Though I'm not sure whether shared hooks should be able to modify it (or the params).
also, we need better names than shared/exclusive.

Also also, GetIsCalledBy() is totally unrelated, should be a separate issue.
