### ISSUE TITLE
Transfer nwn 1.69 to EE via NWNX

### ISSUE THREAD

**Issue by navvator** [nwnxee/unified#666]
Hello. I am try transfer nwn1.69 nxnx windows to nwn EE nwnxEE linux x86. Server work, i can login and play and my sql database is connect (they are loot from mobs, etc), but loot  dont work... and all database sql funcs... Whats can be wrong?

**Comment by mtijanic** [comment]
The API is different, your scritps will need to be edited. For SQL, take a look here for what the new functions look like:
https://github.com/nwnxee/unified/blob/master/Plugins/SQL/NWScript/nwnx_sql.nss

you will find a small migration guide here: 
https://github.com/nwnxee/unified/blob/master/Plugins/SQL/Migration_Guide.md

If you're using `aps_include`, you can just modify that file to act as a wrapper for the new NWNX functions, with something like:
```C
void SQLInit()
{
/* nothing */
}
 
void SQLExecDirect(string sSQL)
{
    NWNX_SQL_ExecuteQuery(sSQL);
}
 
int SQLFetch()
{
    if (!NWNX_SQL_ReadyToReadNextRow())
        return SQL_ERROR;

    NWNX_SQL_ReadNextRow();
    return SQL_SUCCESS;
}
 
string SQLGetData(int iCol)
{
    if (iCol == 0) return "";
    return NWNX_SQL_ReadDataInActiveRow(iCol - 1);
}
```

**Comment by navvator** [comment]
Thank you. Another quastion:  Where i must put folder with my dynamic scripts? new nwnx have not this option?

**Comment by mtijanic** [comment]
For dynamic scripts, you need to wait until the next NWN patch and 64bit. Then you can put them either in `development/` or in `nwnx/` folders.

If you're just testing, you can use the 64bit branch and 8192 NWN dev build, but very few people will be able to connect to your server because they are on older, stable version.

We expect the NWN to update to 64bit very soon, and then everyone will move over.

**Comment by navvator** [comment]
Thank you. Problem solved.

**Comment by mtijanic** [comment]
"Problem solved."
