### ISSUE TITLE
Regarding C++ guidelines #4

### ISSUE THREAD

**Issue by jd28** [nwnxee/unified#715]
"4.  Never use non-const references as arguments. If a function will change the value of an object, pass it as a pointer."

I'm curious why this would be codified.  Personally, I think Config, for example (I have a pr gathering dust), would have been better off using a templated non-const reference parameter rather than template specializations on Maybe/std::optional return types.  Pointers could be used in that scenario too, but I don't see introducing a possible `null` as pure win.

**Comment by jd28** [comment]
On second thought there would have been no need for templates in the inout parameter scenario, bog standard function overloading would have worked just fine.

**Comment by mtijanic** [comment]
> I'm curious why this would be codified

The reason it is codified is the case of:
```C
int n = 3;
foo(n);
assert(n == 3);
```
When reading the code and come across `foo(n)`, there is no way to know whether it's passed by (non-const) reference or by value, and as such no way to know if n changes without checking the declaration of `foo`. This is extreme mental overhead, and I've had bugs with such code before. It applies to other types as well, objects or PODs.
When you see `foo(&n)` it is very obvious that it's going to change the value.

Overloads beat template functions for e.g. `Config::Set()`, but the `std::optional`-returning `Config::Get()` can't be overloaded, since it differs only in return type. I would not at all be opposed to changing `auto thingy = config->Get<std::string>("THINGY")` to `auto thingy = config->GetString("THINGY")`, but I didn't feel to strongly about it (and didn't think too hard about it) to include it in the guidelines.

**Comment by jd28** [comment]
Fair enough.  I was thinking of this kind of use case (pointers could work here too of course) that's nicer (imo) than template specializations on return types:

```c++
bool GetConfig(const string& plugin, const string& key, int& inout); // etc... 
```

But it's really neither here nor there really,, it's not what my PR will be about.

**Comment by jd28** [comment]
Oops, meant to close this.

**Comment by jd28** [comment]
Re-opening this because there are examples in the codebase that do not follow this guideline.  Viz Events::InsertArgument(s).

**Comment by mtijanic** [comment]
Yep. I'd actually prefer if we just changed all the code to be
```C
return Events::ArgumentStack{arg1, arg2, arg3};
```
just need to have a strong guarantee of left-to-right or right-to-left - whatever people feel more intuitive.

**Comment by jd28** [comment]
i like it but -- and i am sliding seriously off topic -- but i don't really get the value of destroying the argstack storage every call/return.

**Comment by mtijanic** [comment]
I'm gonna close this issue as we've gone off track from the original intent. Feel free to re-open if you want to debate the guidelines themselves.
For any remaining code that is not following the guidelines, we can open a new issue.
