### ISSUE TITLE
Contributing code : IDE / Dev environment setup?

### ISSUE THREAD

**Issue by Baaleos** [nwnxee/unified#744]
Hi - is there any specific IDE or development environment recommended for contributing?
When I did some nwnx development on the win32 platform - I had access to visual studio + intellisense etc
Just wondering if there is a different recommended IDE or setup to use?

Either on osX or Windows environment?

**Comment by GoLoT** [comment]
I'm currently using VS as my IDE, WSL2 for debugging (it runs almost as if running natively, no issues with gdb so far) and docker over WSL2 for running nwserver instances.
Previously I used CLion because it made it a lot easier to set up remote development, which I needed because I was remotely debugging using a linux box (couldn't run 32 bit binaries on WSL), but the WSL integration in VS is pretty nice once you get it working and nwserver can be run on WSL now.

If you are going to develop on Windows I recommend joining insiders and downloading the slow ring update that includes WSL2. WSL should do too since nwserver is 64 bits now. If you need help setting up the environment I may be able to help.

**Comment by Daztek** [comment]
I'm using a linux VM + Jetbrain's CLion, might switch to something else + WSL2 once that's not Insider only anymore.

**Comment by mtijanic** [comment]
Closing as non-actionable. Feel free to reopen if there's further questions.
