### ISSUE TITLE
[proposal] [Dialog] Use the conversation node Comments field to support per-node variables

### ISSUE THREAD

**Issue by shadguy** [nwnxee/unified#784]
**NWN2** allows setting variables on conversation nodes to driven script behavior (and minimize script count).  **NWN1** does not, but we do have a _Comments_ field for every node in a conversation.  

**Idea**: Can we read the _Comment_ field and use this to drive conversation script behavior per node?

For example, maybe a mod designer sticks something like this in their comment for a given conversation node:

```
conversationNodeVariables {
   int ItemCount = 10;   
   string ItemResref = "my_mob_drop";
   float someDemoFloat = 1.1134;      // just an illustration
}
```
The idea above is the int and string vars could drive a re-useable script to check if a player has retrieved item drops to fullfill some quest requirement, for example, variations on the classic "bring me rat tails from the sewers" L1 quest trope.  The float is just a supplemental demo.

NWNX could look into providing a string GetDialogNodeComment() function, which could return the whole Comment for parsing in nwscript.  Or, if we're more ambitious, we could parse the vars in NWNX to provide a more complete solution.  (ie. GetConversationNodeInt/String/Float() )

I wouldn't even know where to begin on a project like this, but think the idea has a enough merit to suggest.  Feedback welcome.  I expect the whole thing will become obsolete if BeamDog chases the NWN2 feature, but I've not insight into possibilities there.  Plus, if it works, this doesn't require toolset enhancements (win).

**Comment by GoLoT** [comment]
Just my 2 cents: I don't know much about the conversation system but if the comment field is used this way `RunScriptChunk()` seems like a better choice than parsing the string in nwscript. A whole custom script can be run that way or it can be used to call an existing script passing the parameters with something like `#include "yourscript" YourFunction(10, "my_mob_drop", 1.1134);`.

**Comment by Daztek** [comment]
I don't think we can get at the comment fields through nwnx, they're only really for the benefit of the toolset user :(

**Comment by shadguy** [comment]
GoLot, good idea!

Daz, sounds like we're dead in the water, anyway.  Thanks for the feedback.  I guess we can shut this down.

**Comment by mtijanic** [comment]
Reopening with 'unlikely' tag for now, since this _is_ possible, though I haven't yet looked into how exactly. But theoretically it _has to be_ possible.

**Comment by GoLoT** [comment]
`CNWSDialog::LoadDialog()` doesn't read the comment fields and `CNWSDialogEntry` doesn't have any unused members that can be used to store a `char*` to hold the value. The hooking part should be straightforward (LoadDialog() shared hook, after: loop through all entries and read their comments) but finding a way to store the comment not so much.

Since CNWSDialogs are used on the spot and not kept in an array or list, keeping a map of `CNWSDialog` -> `commentList` is not that easy. Maybe a map that links the pointer address to a list of comments and the entry is removed when CNWSDialog::~CNWSDialog()` is called, but that isn't too clean.

Another option would be to store it in `CNWSDialogEntry->m_sScript` if a specific header (i.e. "##--") is set in the comment field. An example:
```
##-- choiceScript
Custom text that
you saved in the comment
``` 
Whenever the `m_sScript` member is accessed, if the content starts with "##--" the first line is parsed to get the script name (`choiceScript`) and used accordingly. Whenever you want to access the comment content, you get the content of `m_sScript` skipping the first line.

This requires hooking and rewriting any function that uses `m_sScript` but is the only easy solution I can come up with.

This is probably not the way to do it but I'm just throwing ideas.

**Comment by mtijanic** [comment]
`m_sScript` is `CResRef`, so it will only contain 16 characters. However, we can add the script snippet as an alternative language in the `CExoLocString` (any unused language ID).

**Comment by shadguy** [comment]
Given features seen in the .14 preview build, I'm closing this, as it targets the same application as adding vars to convo nodes.
-Dave
