### ISSUE TITLE
[Feature request] NWNX_Damage_SetDamageEventScript - fire on placeables

### ISSUE THREAD

**Issue by Txpple** [nwnxee/unified#829]
Hello,

NWNX_Damage_SetDamageEventScript only fires on creatures.  It does not fire on placeables.

Conversely, NWNX_Damage_SetAttackEventScript fires on both creatures AND placeables.

Would it be possible to make NWNX_Damage_SetDamageEventScript  fire on both placeables, too, and have consistent behavior for the two functions.  Thank you!

**Comment by Baaleos** [comment]
When I made the original version of the damage plugin on win32 - I don't think I applied a creature filter to it and it seemed to work fine - I guess its because the engine has already determined that the object having damage applied to, is valid already.
I suspect the creature restriction was added as an attempt to lower the call rate to the nss damage script.

It should be safe to add placeable to the filter - in order to have it fire for creatures and placeables etc.

**Comment by plenarius** [comment]
This was resolved with #1027
