### ISSUE TITLE
Some crash backtraces from 8193.10 and after reverting in 8193.9

### ISSUE THREAD

**Issue by vaardu** [nwnxee/unified#864]
Some selection of backtraces from 8193.10 we had before we eventually reverted back to 8193.9, in case there might be something of use.

**8193.10** 
[nwnx_crash_21_4_2020_a.txt](https://github.com/nwnxee/unified/files/4531422/nwnx_crash_21_4_2020_a.txt)
[nwnx_crash_21_4_2020_b.txt](https://github.com/nwnxee/unified/files/4531423/nwnx_crash_21_4_2020_b.txt)
[crast_21_4_2020_c.txt](https://github.com/nwnxee/unified/files/4531425/crast_21_4_2020_c.txt)
[crash_22_04_2020.txt](https://github.com/nwnxee/unified/files/4531427/crash_22_04_2020.txt)

Now what we had lately after near two days since going back to **8193.9**
[crash_24_04_2020.txt](https://github.com/nwnxee/unified/files/4531429/crash_24_04_2020.txt)

**Comment by GoLoT** [comment]
All crashes seem to be related to corrupted pointers. Either dangling pointers or variables filled with garbage that are treated as valid pointers. It's out of my expertise but that's the conclusion I draw from looking at the logs. If I had to guess I'd say it's a memory corruption issue of some kind.

But it doesn't make sense that it's only happening in .10. In any case, I'll leave a breakdown of each crash.

**nwnx_crash_21_4_2020_a.txt**
This happened when an item inside a container was treated by the engine as a container (`m_pItemRepository != null`) but for some reason the item list in that item repository (`m_oidItems`) wasn't initialized, crashing when dereferencing the item list pointer.

Since the item list is initialized in the `CItemRepository` constructor I don't see how this can happen.

**nwnx_crash_21_4_2020_b.txt**
This one is weird too, it happened when dereferencing `this->m_sDamageDebugText` in `CNWSCombatAttackData::ClearAttackData(CNWSCombatAttackData *this)`.

**crast_21_4_2020_c.txt**
Similar to the previous one, crashed while dereferencing `this->m_sDamageDebugText` but this time in `CNWSCombatAttackData::~CNWSCombatAttackData(CNWSCombatAttackData *this)`.

**crash_22_04_2020.txt**
Same as _nwnx_crash_21_4_2020_b.txt_

**crash_24_04_2020.txt**
```
CNWSArea::ComputeSafeLocation()
CNWSCreature::RealizeAssociateList()
CServerExoAppInternal::MovePlayerToArea()
CNWSMessage::HandlePlayerToServerAreaMessage()
CNWSMessage::HandlePlayerToServerMessage()
CServerExoAppInternal::HandleMessage()
```
Crashed while dereferencing `CNWSArea::m_pSearchInfo` for an area that was null-guarded.

**Comment by vaardu** [comment]
One additional trace I got in 8193.9 version crash earlier.

[crash_02_05_2020.txt](https://github.com/nwnxee/unified/files/4567942/crash_02_05_2020.txt)

**Comment by mtijanic** [comment]
> One additional trace I got in 8193.9 version crash earlier.
> 
> [crash_02_05_2020.txt](https://github.com/nwnxee/unified/files/4567942/crash_02_05_2020.txt)

Same as crash_24_04_2020. The only thing I get from there is that player transitioned into an invalid area. Possibly the area was deleted while the player was in a loadscreen?

**Comment by vaardu** [comment]
Thank you very much. You guys are very helpful, as I don't know how to read these. Gives some indication on what to consider or try to look at, the very least.

**Comment by vaardu** [comment]
Closing this issue to avoid having duplicates, same issues are reported on the following issue after having updated to 8193.13
Found here: #907
