### ISSUE TITLE
Fatal error: Segmentation fault (11), Program aborted (6)

### ISSUE THREAD

**Issue by WmRickert1** [nwnxee/unified#900]
basic_string::_M_construct null not valid
![Capture](https://user-images.githubusercontent.com/65330688/81899718-1098f180-9581-11ea-881d-e233b96f59c4.PNG)

**Comment by mtijanic** [comment]
We're gonna need a bit more information. What do the logs say before that? How are you starting nwnx? Which platform?

**Comment by WmRickert1** [comment]
NWNX:EE on WSL1

![Capture](https://user-images.githubusercontent.com/65330688/81900193-f9a6cf00-9581-11ea-88b6-a9b4ace932f7.PNG)
![Capture](https://user-images.githubusercontent.com/65330688/81900229-075c5480-9582-11ea-8f59-aa9b33016e37.PNG)

**Comment by WmRickert1** [comment]
![Capture](https://user-images.githubusercontent.com/65330688/81900357-38d52000-9582-11ea-9edc-51df1ec2ad49.PNG)

**Comment by WmRickert1** [comment]
How are you starting nwnx?
./run-server.sh

**Comment by WmRickert1** [comment]
Thx clippy

**Comment by mtijanic** [comment]
There is an "Unable to load module" before the crash, meaning something is not right with the setup regardless of nwnx. Please double check that:
1. The module name is exactly "Anphillia Classic _03L"  (Hey, another anph module!)
2. All your haks and tlks are in the correct place
3. All your extensions are lowercase

Note that Linux is case sensitive, so "Anphillia" is different from "anphillia" and "ANPHILLIA". Same for haks and the tlk.


I'll look into why it's crashing, but it is crashing only on shutdown, your problem is much earlier than that.

**Comment by WmRickert1** [comment]
Well everyone hates CNR so I pulled my private ATS version out. I guess Moth is done. Hopefully alive.

I  ^c  ^v  everything but I'll check my pathing.

Does this install and run MySql? I have a statement on load to create the tables. 
I assumed so. I converted from tokens to MySql 6-8 years ago.

**Comment by mtijanic** [comment]
The issue is before mysql, and before nwnx actually does anything. You will have the same issue with base server without nwnx. Unfortunately, base game is not very helpful with the "Failed to load module", but maybe userdir/logs0/nwserverError.log or similar will have more info.
This is the first problem you need to solve and then worry about everything else.

**Comment by WmRickert1** [comment]
Not sure if it helps. Prior to update it ran on NWNx2 Win 7 before update and recompile. 

Updated module by dropping scripts in temp(0) then building.

**Comment by WmRickert1** [comment]
> 
> 
> The issue is before mysql, and before nwnx actually does anything. You will have the same issue with base server without nwnx. Unfortunately, base game is not very helpful with the "Failed to load module", but maybe userdir/logs0/nwserverError.log or similar will have more info.
> This is the first problem you need to solve and then worry about everything else.

I can work with this. Thanks

**Comment by WmRickert1** [comment]
Hold on. That's on Unbuntu not winduhz right?

**Comment by mtijanic** [comment]
> Updated module by dropping scripts in temp(0) then building.

Scripts themselves wouldn't break it, but if you added/removed areas this way it might have broken it. Try just loading the mod on windows (e.g. in singleplayer) and see if that works. If that fails, the mod got corrupted somehow and you need to fix that/revert to older version.
A corrupted module would give the same error message.

**Comment by WmRickert1** [comment]
Yeah, this is a bugger. 

I'm running fine on winduhz no errors, using the native server client that comes with the game. No NwNx though. Full test success, took character to lvl 4.

I've tried this with several modules, including CEP modules. 
Same result. 

Stock Server runs. Packaged EE server won't run any modules. 


I ran an update. 
Then replicated the bug.

**Comment by WmRickert1** [comment]
Something is missing from the setup doc. Please review prerequisites, and all tiny stupid details. I don't know this package well enough yet to assist.

**Comment by Daztek** [comment]
Make sure the paths in [Section 7](https://github.com/Daztek/NWNX-WSL#7-setting-up-aliases) are  set up correctly.

**Comment by WmRickert1** [comment]
Yessir, I'm looking at configuration and pathing. 

I'll set up the APS/ATS DB tables manually too since I can't fire the build it through the module this time. 
Give me a couple days. 
Work...

**Comment by WmRickert1** [comment]
PEBKAC

Layer 8 issue. Thanks.
