### ISSUE TITLE
[Feature Request] Scripting: Get/SetLocalStruct

### ISSUE THREAD

**Issue by Christian-Vassallo** [nwnxee/unified#986]
Hello everybody,

what do you think about SetLocalStruct / GetLocalStruct / DeleteLocalStruct function?

Do you think that would be possible to have them?

**Comment by Chimerik** [comment]
What would the use case be?

Personnally, I would use the new sqlite functions added to the core game in .14 in order to store and create struct like data.

**Comment by Daztek** [comment]
Not possible I'm afraid, afaik. Your best bet is writing your own wrappers that use the other Get/SetLocalXXX functions. Or as Chimerik says, use the new sqlite functionality coming in 8193.14.

**Comment by mtijanic** [comment]
@Christian-Vassallo Consider that NWNX can expose additional _functions_ to nwscript, but it does not extend the nwscript language itself. With that in mind, try to think of how a function like you are requesting would look like? It is simply not possible to write such a function in a way nwscript can consume it. The only way to do it would be to extend the language, such as through `nwnsc` compiler, but then you would no longer be able to compile those scripts in the toolset.

I do mean this, honestly. It is really a good learning experience to think about exactly what it would look like and why it is simply not possible.

(closing since it really is not possible)
